### ISSUE TITLE
Help with Machine Vision on VMX

### ISSUE THREAD

**Issue by SulimovMikhail** [studica/studica-docs-worldskills#13]
Hello Friend
I really need your help: I am trying to program a robot based on a VMX with the help of LabView. I really need a vi for color analysis (ColorLearn.vi) could you send this vi to my email IgorZaitcev74@yandex.ru ?

**Comment by Jm-Taylor** [comment]
I can't give you the code you are looking for. However, if you have the beta version LabVIEW installed as per this documentation then in the HG_Vision_Toolkit you will have some color processing vis. These vi's are ColorThreshold, cvtColor, and ColorHistogram.

**Comment by Londau** [comment]
Good afternoon.  I'm sorry to trouble you.  Tell me, is there any documentation for the hg vision toolkit?  Learning to work with vmx in labview.  There are many unclear points
