### ISSUE TITLE
controlling the motor

### ISSUE THREAD

**Issue by DGDL** [studica/studica-docs-worldskills#2]
Ask if there is a routine for controlling the motor

**Comment by Jm-Taylor** [comment]
Hi DGDL,

The documentation for controlling the motor is on the list to be added soon.

Thanks
James

**Comment by Jm-Taylor** [comment]
Motor documentation has been updated and is available now in the docs.

**Comment by DGDL** [comment]
I see the documentation, thank you

**Comment by DGDL** [comment]
> 电机文档已更新，现在可在文档中找到。

I see the documentation, thank you

**Comment by DGDL** [comment]
> Motor documentation has been updated and is available now in the docs.

see the documentation, thank you

**Comment by DGDL** [comment]
> Motor documentation has been updated and is available now in the docs.

I have a question, can I write FPGA

**Comment by DGDL** [comment]
> Motor documentation has been updated and is available now in the docs.

I read the documentation, thank you

**Comment by Jm-Taylor** [comment]
There is no FPGA anymore.

**Comment by DGDL** [comment]
> There is no FPGA anymore.

 I see. Thank you
