### ISSUE TITLE
VMX-pi HAL Library for arm64?

### ISSUE THREAD

**Issue by mobilerobotics1111** [studica/studica-docs-worldskills#29]
Hello

I found out that the VMX-pi HAL library only works with armhf.
Is there an arm64 version of the library?

**Comment by Jm-Taylor** [comment]
Hi,

We compiled an arm64 a little while ago for some teams that wanted to use ROS on Ubuntu. However, only the cpp HAL is available for this build.

https://studicalimited.sharepoint.com/:f:/s/SR-Resources/EhIZFplb6R9LsR4TJyYUm5gBxVp78zb3BPnIVt3qs1dXBw?e=cqUMWg

username & password for the image is "ubuntu"
