### ISSUE TITLE
I accidentally put VMXpi firmware on TITAN，I need the firmware for Titan.

### ISSUE THREAD

**Issue by PTA00** [studica/studica-docs-worldskills#6]
@Jm-Taylor An offline HEX file is needed because Titan cannot be connected.

**Comment by CrackAndDie** [comment]
Hello, @PTA00 . I had the same problem. I thought that when I install *Studica Config & Update App* I will find somewhere on my computer *Titan quad* firmware as ```.hex``` file. But I didn't. So I made some manipulations with a normal *Titan quad* and now I have an ```.hex``` file with the firmware. I don't know why studica doesn't give us this files. Feel free to use it.
[titan_firmware_2.txt](https://github.com/studica/studica-docs-worldskills/files/7013668/titan_firmware_2.txt). (But you should rename it into ```.hex```, cause github didn't let me to unload ```.hex``` file)

**Comment by PTA00** [comment]
@CrackAndDie Thank you。But I have it now,This is the latest version of the firmware:[Titan_Quad_1_0_0.zip](https://github.com/studica/studica-docs-worldskills/files/7013752/Titan_Quad_1_0_0.zip)

I sent them an email.They told me to go to the website and create work orders.
And then I get this file.
without a hitch.

**Comment by PTA00** [comment]
Note: If the sample program does not work properly, it may be the firmware problem, please reset the firmware.

**Comment by CrackAndDie** [comment]
ok, thank you too :)

**Comment by rustiksnex** [comment]
what to do if the firmware is up but does not want to be updated over the Internet. and the program does not display the ID 42 titan in the drop-down list?

**Comment by rustiksnex** [comment]
что делать если прошивка встала но не хочет обновляться по интернету. и в программе не отображается ID 42 titan в выпадающем списке?
